services:
  - type: web
    name: riceguard-frontend
    env: node
    plan: free
    buildCommand: |
      cd frontend
      npm i
    startCommand: |
      cd frontend
      npm run dev
    envVars:
      - key: PORT
        value: 3000

  - type: web
    name: riceguard-backend
    env: node
    plan: free
    buildCommand: |
      cd backend
      npm i
    startCommand: |
      cd backend
      npm run dev

  - type: web
    name: riceguard-api
    env: python
    plan: free
    buildCommand: |
      cd api
      pip install -r requirements.txt
    startCommand: |
      cd api
      uvicorn app:app --host 0.0.0.0 --port 5000 --reload
