services:
  - type: web
    name: riceguard-frontend
    env: node
    plan: free
    buildCommand: |
      cd frontend
      yarn install
    startCommand: |
      cd frontend
      yarn start

  - type: web
    name: riceguard-backend
    env: node
    plan: free
    buildCommand: |
      cd backend
      yarn install
    startCommand: |
      cd backend
      yarn start

  - type: web
    name: riceguard-api
    env: python
    plan: free
    buildCommand: |
      cd api
      pip install -r requirements.txt
    startCommand: |
      cd api
      uvicorn app:app --host 0.0.0.0 --port 10000 --reload
