services:
  - type: web
    name: skisen-frontend
    runtime: node
    plan: free
    buildCommand: |
      cd frontend
      npm install
    startCommand: |
      cd frontend
      npm run start

  - type: web
    name: skisen-backend
    runtime: node
    plan: free
    buildCommand: |
      cd backend
      npm install
    startCommand: |
      cd backend
      npm run start

  - type: web
    name: skisen-api
    runtime: python
    plan: free
    buildCommand: |
      cd api
      pip install -r requirements.txt
    startCommand: |
      cd api
      uvicorn app:app --host 0.0.0.0 --port 10000 --reload
